### ISSUE TITLE
The project does not compile (maven or gradle files are missing)

### ISSUE THREAD

**Issue by bruce-forte** [julianmaster/AsciiTerminal#1]
There is no maven or gradle metadata in the project. In its current form it won't compile.

**Comment by julianmaster** [comment]
This is not a complete project for LibGDX. This is just the content of the core part. I have done this because users can use it as they want and extract what interests them.
The goal is simply to provide the basics for a terminal display. People import the library into their projects.
I hope that answered your questions.
